# name: phpapp
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8088:80"
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     restart: always
#     command: -- default-authentication-plugin=mysql_native_password
#     environment :
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: mysqldb
#     volumes :
#       - db_data:/var/lib/mysql


name: phpapp
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    #networks:
      #phpappnet:

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    #networks:
      #phpappnet:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    #networks:
      #phpappnet:

#networks:
  #phpappnet:

volumes:
  db_data:


